### ISSUE TITLE
Filtering breaks when using pagination

### ISSUE THREAD

**Issue by atgillette** [valor-software/ng2-table#397]
Hi,

I've downloaded the latest version on github and ran the demo.  When I paginate to another page and try to use a search on a filter, I get the following error:

`EXCEPTION: Error in ./TableDemoComponent class TableDemoComponent - inline template:12:10 caused by: Expression has changed after it was checked. Previous value: ''. Current value: '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'.`

But when I do the same thing on http://valor-software.com/ng2-table/, I'm not getting any errors.

**Comment by webcat12345** [comment]
You got that because you are not handling the change exception.
here is solution : 



`import { ChangeDetectorRef } from '@angular/core';`

```
 constructor (
    ... ...
    private ref: ChangeDetectorRef
    ...  ...
  ) {
   ... ...
  }
```

```
public onChangeTable(...):any {
    ...   ....  ...
    this.ref.detectChanges();
  }
```

**Comment by atgillette** [comment]
Thanks @webcat12345,

That did it.  Should I submit a pull request for this?

**Comment by webcat12345** [comment]
No need to do that. other developers will check this forum and they will avoid this issue.

**Comment by atgillette** [comment]
Okay.  Closing this issue.

Thanks for your help.

**Comment by danny-swimmer** [comment]
@webcat12345 - When I try your solution I get this exception:

EXCEPTION: Uncaught (in promise): Error: Error in ./LogsComponent class LogsComponent - inline template:0:12 caused by: Cannot read property 'config' of undefined
Error: Error in ./LogsComponent class LogsComponent - inline template:0:12 caused by: Cannot read property 'config' of undefined
    at ViewWrappedError.Error (native)
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:144080:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:7102:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:7167:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:68688:16)
    at DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:101863:23)
    at DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:101836:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:69655:20)
    at LogsComponent.webpackJsonp.523.LogsComponent.onChangeTable (http://localhost:4200/main.bundle.js:2144:18)
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:2061:81)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/vendor.bundle.js:576:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:518:27)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:469:26)
    at Subscriber.next (http://localhost:4200/vendor.bundle.js:433:18)
    at BehaviorSubject._subscribe (http://localhost:4200/vendor.bundle.js:27615:24)

**Comment by priyakokas** [comment]
Wonderful work webcat12345 :)
