### ISSUE TITLE
ng-table-module component is empty when installing v1.3.2 via package.json

### ISSUE THREAD

**Issue by jonsabogal** [valor-software/ng2-table#405]
Running the npm install command fails on my end for some reason. So I installed ng2-table v1.3.2 via package.json file and then restoring packages. I imported Ng2TableModule as instructed but received some errors, and then when I open up the Ng2TableModule class, it has nothing in it except for the class declaration. In contrast, this class contains additional content when looking at the source code in github. I've attempted deleting and restoring packages twice, with the same results. A workaround would be to download the files, however my project is shared with other people using Git, and we rely on package.json to restore packages when somebody else adds a new package to the project. Any help is appreciated thanks.

**Comment by webcat12345** [comment]
Please let me know why `npm install` does not work and which error you ve got while importing Module.

**Comment by jonsabogal** [comment]
Here is the error I receive from the browser (chrome):

`localhost/:17 Error: (SystemJS) Unexpected value 'undefined' imported by the module 'SharedModule'
	Error: Unexpected value 'undefined' imported by the module 'SharedModule'
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14131:33)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at RuntimeCompiler._compileComponents (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:16803:49)
	Evaluating http://localhost:31514/app/main.js
	Error loading http://localhost:31514/app/main.js
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14131:33)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at eval (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
	    at RuntimeCompiler._compileComponents (http://localhost:31514/node_modules/@angular/compiler/bundles/compiler.umd.js:16803:49)
	Evaluating http://localhost:31514/app/main.js
	Error loading http://localhost:31514/app/main.js`

This is the js file loaded to the browser: http://localhost:31514/node_modules/ng2-table/bundles/ng2-table.js  (this is an ng2 app on top of an asp.net core web app, and I am sending the npm dependencies to the wwwroot folder via a gulp.js file).

In systemjs config file, I have the following mapping:
'ng2-table':'node_modules/ng2-table/bundles/ng2-table.js'
(I'd think this should be the target js file, but mapping to the js file directly under ng2-table folder does not work either.)

Here is my SharedModule mentioned in the error above:

`import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { NgbModule } from "@ng-bootstrap/ng-bootstrap";
import { CrgbFilterComponent } from "./components/crgb-filter.component";
import { DateFilterComponent } from "./components/date-filter.component";
import { ChartsModule } from "ng2-charts/components/charts/charts";
import { PieChartComponent } from "./components/pie-chart.component";
import { LineChartComponent } from "./components/line-chart.component";
import { DateFilterService } from "./services/date-filter.service";
import { PieChartService } from './services/chart.service';
import { Ng2TableModule } from "ng2-table";

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        NgbModule,
        ChartsModule,
        Ng2TableModule
    ],
    exports: [
        CommonModule,
        FormsModule,
        NgbModule,
        CrgbFilterComponent,
        DateFilterComponent,
        PieChartComponent,
        LineChartComponent,
        ChartsModule,
        Ng2TableModule
    ],
    declarations: [
        CrgbFilterComponent,
        DateFilterComponent,
        PieChartComponent,
        LineChartComponent
    ],
    providers: [
        DateFilterService,
        PieChartService
    ]
})
export class SharedModule { }`

This shared module is imported into the root app module.

The problem may be something else since I pasted the Ng2TableModule typescript code from this github repo into the Ng2TableModule I am importing above, and the same error appears. There are no typescript errors in my IDE. The only problem I get is the error mentioned at the top from the browser. If I were to remove Ng2TableModule from the imports/exports array in my shared module, my app runs OK.

With respect to npm install command - I am not sure what the problem is there (the error thrown is huge and seems very low-level) but it's not working for other npm packages either. This is a work pc with a number of restrictions due to security concerns and my workaround for installing other packages has been to write everything in package.json.

Thanks.

**Comment by jonsabogal** [comment]
I've solved my problem. I had to set up my system js config file differently to target the ng2-table.js file directly inside the ng2-table folder...
