### ISSUE TITLE
please  help me

### ISSUE THREAD

**Issue by zl0711** [valor-software/ng2-table#581]
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'. ("
        <div>

            <input *ngIf="config.filtering" placeholder="Filter all columns" [ERROR ->][ngTableFiltering]="config.filtering" class="form-control" (tableChanged)="onChangeTable(config)" />
"): ng:///AppModule/HomePage.html@120:77
Can't bind to 'config' since it isn't a known property of 'ng-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <br>

    <ng-table [ERROR ->][config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]=""): ng:///AppModule/HomePage.html@128:14
Can't bind to 'rows' since it isn't a known property of 'ng-table'.
1. If 'rows' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [ERROR ->][rows]="rows" [columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:107
Can't bind to 'columns' since it isn't a known property of 'ng-table'.
1. If 'columns' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]="rows" [ERROR ->][columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:121
'ng-table' is not a known element:
1. If 'ng-table' is an Angular component, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <br>

    [ERROR ->]<ng-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)"): ng:///AppModule/HomePage.html@128:4
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("
    </ng-table>

    <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [ERROR ->][totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotat"): ng:///AppModule/HomePage.html@132:79
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("   <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ERROR ->][itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChange"): ng:///AppModule/HomePage.html@132:101
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("aging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [ERROR ->][maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $eve"): ng:///AppModule/HomePage.html@132:131
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("tion-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [ERROR ->][boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="num"): ng:///AppModule/HomePage.html@132:151
Can't bind to 'rotate' since it isn't a known property of 'pagination'. ("age" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [ERROR ->][rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="numPages = $event">

    <"): ng:///AppModule/HomePage.html@132:174
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </ng-table>

    [ERROR ->]<pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ite"): ng:///AppModule/HomePage.html@132:4 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'. ("
        <div>

            <input *ngIf="config.filtering" placeholder="Filter all columns" [ERROR ->][ngTableFiltering]="config.filtering" class="form-control" (tableChanged)="onChangeTable(config)" />
"): ng:///AppModule/HomePage.html@120:77
Can't bind to 'config' since it isn't a known property of 'ng-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <br>

    <ng-table [ERROR ->][config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]=""): ng:///AppModule/HomePage.html@128:14
Can't bind to 'rows' since it isn't a known property of 'ng-table'.
1. If 'rows' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [ERROR ->][rows]="rows" [columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:107
Can't bind to 'columns' since it isn't a known property of 'ng-table'.
1. If 'columns' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]="rows" [ERROR ->][columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:121
'ng-table' is not a known element:
1. If 'ng-table' is an Angular component, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <br>

    [ERROR ->]<ng-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)"): ng:///AppModule/HomePage.html@128:4
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("
    </ng-table>

    <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [ERROR ->][totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotat"): ng:///AppModule/HomePage.html@132:79
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("   <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ERROR ->][itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChange"): ng:///AppModule/HomePage.html@132:101
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("aging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [ERROR ->][maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $eve"): ng:///AppModule/HomePage.html@132:131
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("tion-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [ERROR ->][boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="num"): ng:///AppModule/HomePage.html@132:151
Can't bind to 'rotate' since it isn't a known property of 'pagination'. ("age" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [ERROR ->][rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="numPages = $event">

    <"): ng:///AppModule/HomePage.html@132:174
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </ng-table>

    [ERROR ->]<pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ite"): ng:///AppModule/HomePage.html@132:4
    at syntaxError (http://localhost:8100/build/vendor.js:105081:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:115572:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:129323:39)
    at http://localhost:8100/build/vendor.js:129247:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:129247:19)
    at createResult (http://localhost:8100/build/vendor.js:129132:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076 Error: Template parse errors:
Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'. ("
        <div>

            <input *ngIf="config.filtering" placeholder="Filter all columns" [ERROR ->][ngTableFiltering]="config.filtering" class="form-control" (tableChanged)="onChangeTable(config)" />
"): ng:///AppModule/HomePage.html@120:77
Can't bind to 'config' since it isn't a known property of 'ng-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <br>

    <ng-table [ERROR ->][config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]=""): ng:///AppModule/HomePage.html@128:14
Can't bind to 'rows' since it isn't a known property of 'ng-table'.
1. If 'rows' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [ERROR ->][rows]="rows" [columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:107
Can't bind to 'columns' since it isn't a known property of 'ng-table'.
1. If 'columns' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]="rows" [ERROR ->][columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:121
'ng-table' is not a known element:
1. If 'ng-table' is an Angular component, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <br>

    [ERROR ->]<ng-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)"): ng:///AppModule/HomePage.html@128:4
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("
    </ng-table>

    <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [ERROR ->][totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotat"): ng:///AppModule/HomePage.html@132:79
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("   <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ERROR ->][itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChange"): ng:///AppModule/HomePage.html@132:101
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("aging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [ERROR ->][maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $eve"): ng:///AppModule/HomePage.html@132:131
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("tion-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [ERROR ->][boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="num"): ng:///AppModule/HomePage.html@132:151
Can't bind to 'rotate' since it isn't a known property of 'pagination'. ("age" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [ERROR ->][rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="numPages = $event">

    <"): ng:///AppModule/HomePage.html@132:174
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </ng-table>

    [ERROR ->]<pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ite"): ng:///AppModule/HomePage.html@132:4
    at syntaxError (http://localhost:8100/build/vendor.js:105081:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:115572:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:129323:39)
    at http://localhost:8100/build/vendor.js:129247:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:129247:19)
    at createResult (http://localhost:8100/build/vendor.js:129132:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
n.onUnhandledError @ polyfills.js:3
r @ polyfills.js:3
(anonymous) @ polyfills.js:3
n.microtaskDrainDone @ polyfills.js:3
o @ polyfills.js:3
Promise resolved (async)
r @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMicroTask @ polyfills.js:3
f @ polyfills.js:3
t.then @ polyfills.js:3
setDriver @ localforage.js:2234
LocalForage @ localforage.js:2040
4.3 @ localforage.js:2296
s @ localforage.js:7
e @ localforage.js:7
(anonymous) @ localforage.js:7
i @ localforage.js:7
(anonymous) @ localforage.js:7
(anonymous) @ vendor.js:139403
__webpack_require__ @ bootstrap dd0279650b873f0790c2:54
(anonymous) @ vendor.js:136870
__webpack_require__ @ bootstrap dd0279650b873f0790c2:54
helpers.noop @ vendor.js:54471
__webpack_require__ @ bootstrap dd0279650b873f0790c2:54
411 @ main.ts:5
__webpack_require__ @ bootstrap dd0279650b873f0790c2:54
406 @ main.js:1288
__webpack_require__ @ bootstrap dd0279650b873f0790c2:54
webpackJsonpCallback @ bootstrap dd0279650b873f0790c2:25
(anonymous) @ main.js:1
polyfills.js:3 Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'. ("
        <div>

            <input *ngIf="config.filtering" placeholder="Filter all columns" [ERROR ->][ngTableFiltering]="config.filtering" class="form-control" (tableChanged)="onChangeTable(config)" />
"): ng:///AppModule/HomePage.html@120:77
Can't bind to 'config' since it isn't a known property of 'ng-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <br>

    <ng-table [ERROR ->][config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]=""): ng:///AppModule/HomePage.html@128:14
Can't bind to 'rows' since it isn't a known property of 'ng-table'.
1. If 'rows' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [ERROR ->][rows]="rows" [columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:107
Can't bind to 'columns' since it isn't a known property of 'ng-table'.
1. If 'columns' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]="rows" [ERROR ->][columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:121
'ng-table' is not a known element:
1. If 'ng-table' is an Angular component, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <br>

    [ERROR ->]<ng-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)"): ng:///AppModule/HomePage.html@128:4
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("
    </ng-table>

    <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [ERROR ->][totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotat"): ng:///AppModule/HomePage.html@132:79
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("   <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ERROR ->][itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChange"): ng:///AppModule/HomePage.html@132:101
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("aging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [ERROR ->][maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $eve"): ng:///AppModule/HomePage.html@132:131
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("tion-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [ERROR ->][boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="num"): ng:///AppModule/HomePage.html@132:151
Can't bind to 'rotate' since it isn't a known property of 'pagination'. ("age" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [ERROR ->][rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="numPages = $event">

    <"): ng:///AppModule/HomePage.html@132:174
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </ng-table>

    [ERROR ->]<pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ite"): ng:///AppModule/HomePage.html@132:4
Error: Template parse errors:
Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'. ("
        <div>

            <input *ngIf="config.filtering" placeholder="Filter all columns" [ERROR ->][ngTableFiltering]="config.filtering" class="form-control" (tableChanged)="onChangeTable(config)" />
"): ng:///AppModule/HomePage.html@120:77
Can't bind to 'config' since it isn't a known property of 'ng-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <br>

    <ng-table [ERROR ->][config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]=""): ng:///AppModule/HomePage.html@128:14
Can't bind to 'rows' since it isn't a known property of 'ng-table'.
1. If 'rows' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [ERROR ->][rows]="rows" [columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:107
Can't bind to 'columns' since it isn't a known property of 'ng-table'.
1. If 'columns' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)" [rows]="rows" [ERROR ->][columns]="columns">

    </ng-table>
"): ng:///AppModule/HomePage.html@128:121
'ng-table' is not a known element:
1. If 'ng-table' is an Angular component, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <br>

    [ERROR ->]<ng-table [config]="config" (tableChanged)="onChangeTable(config)" (cellClicked)="onCellClick($event)"): ng:///AppModule/HomePage.html@128:4
Can't bind to 'totalItems' since it isn't a known property of 'pagination'. ("
    </ng-table>

    <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [ERROR ->][totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotat"): ng:///AppModule/HomePage.html@132:79
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'. ("   <pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ERROR ->][itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChange"): ng:///AppModule/HomePage.html@132:101
Can't bind to 'maxSize' since it isn't a known property of 'pagination'. ("aging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [ERROR ->][maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $eve"): ng:///AppModule/HomePage.html@132:131
Can't bind to 'boundaryLinks' since it isn't a known property of 'pagination'. ("tion-sm" [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [ERROR ->][boundaryLinks]="true" [rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="num"): ng:///AppModule/HomePage.html@132:151
Can't bind to 'rotate' since it isn't a known property of 'pagination'. ("age" [totalItems]="length" [itemsPerPage]="itemsPerPage" [maxSize]="maxSize" [boundaryLinks]="true" [ERROR ->][rotate]="false" (pageChanged)="onChangeTable(config, $event)" (numPages)="numPages = $event">

    <"): ng:///AppModule/HomePage.html@132:174
'pagination' is not a known element:
1. If 'pagination' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </ng-table>

    [ERROR ->]<pagination *ngIf="config.paging" class="pagination-sm" [(ngModel)]="page" [totalItems]="length" [ite"): ng:///AppModule/HomePage.html@132:4
    at syntaxError (http://localhost:8100/build/vendor.js:105081:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:115572:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:129323:39)
    at http://localhost:8100/build/vendor.js:129247:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:129247:19)
    at createResult (http://localhost:8100/build/vendor.js:129132:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
    at syntaxError (http://localhost:8100/build/vendor.js:105081:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:115572:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:129323:39)
    at http://localhost:8100/build/vendor.js:129247:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:129247:19)
    at createResult (http://localhost:8100/build/vendor.js:129132:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at c (http://localhost:8100/build/polyfills.js:3:13221)
    at http://localhost:8100/build/polyfills.js:3:14067
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at <anonymous>

**Comment by shiwan66** [comment]
![image](https://user-images.githubusercontent.com/15897892/30626196-d61931b2-9dfa-11e7-9d5b-fb49e9f21502.png)
![image](https://user-images.githubusercontent.com/15897892/30626209-e79f7b80-9dfa-11e7-88bc-39464320b186.png)
